services:
  frontend:
    container_name: frontend
    image: utechzo/ecom-template-1:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    command: [ 'nginx', '-g', 'daemon off;' ]
    ports:
      - 4200:80
    restart: on-failure
    networks:
      - overlay
networks:
    overlay:
        driver: bridge